draft_process:
  description: >
    Develop a detailed workflow outlining the necessary actions to accomplish the task specified in:
    `{input_ask}`
    Break the task into clear, logical, and sequential steps, ensuring the process is well-structured, actionable, and 
    accounts for any dependencies, decision points, or notable considerations.
  expected_output: >
    A comprehensive, well-organized list of process steps. Each step should be concise, easy to 
    follow, and include additional context or substeps as needed to avoid ambiguity. Use numbered lists or nested 
    bullet points to represent hierarchical workflows where applicable.
    Example Output:
    **Process Step Number: Short Description**
      Substep 1: Description ...
      Substep 2: Description ...
      Substep 3: Description ...

capture_assumptions:
  description: >
    Review the detailed process document `{draft_file}` to identify areas with uncertainties, ambiguities, or gaps in the described process. 
    Clearly articulate these areas of uncertainty and develop a well-structured list of assumptions that require clarification.
    Document these assumptions in detail along with their assumed values, if applicable, to provide context for future reference.
    The goal is to ensure all uncertainties are highlighted and refined for accurate process documentation.
  expected_output: >
    Provide a thorough, structured, comprehensive list of well-articulated assumptions addressing identified ambiguities or gaps in the draft process.
    Ensure no critical detail or ambiguity overlooked, laying the groundwork for accurate and complete documentation.
    Each assumption should include the following details:
      - Specific assumption, gap or uncertainty identified
      - Assumed value (if applicable)
      - Related process step(s) where the assumption applies
      - Additional context or explanation for a thorough understanding of the importance and impact on the process
    The list should be detailed and complete, leaving no critical detail or ambiguity unaddressed, providing a strong foundation for accurate and refined process documentation.

clarify_details:
  description: >
    Develop a comprehensive set of targeted, specific questions to gather essential information from the user. This
    aims to identify and address potential ambiguities or missing details within the assumptions listed in
    `{assumptions_file}`. The goal is to minimize assumptions and ensure that all critical information is clarified
    with as few uncertainties remaining unaddressed. These questions should focus on refining the process for accuracy and completeness.
  expected_output: >
    Provide a well-organized list of questions addressing the assumptions identified during analysis.
    Each question should include the following details:
      - Specific questions from the process user's perspective. For example what type of tea should be used when making tea? Or what is the desired serving temperature of the tea?
      - The related assumption, gap or uncertainty identified.
    The list should be detailed and complete, leaving no critical detail or ambiguity unaddressed, providing a strong foundation for accurate and refined process documentation.

reviewed_process:
  description: >
    Consolidate the documents `{draft_file}` and `{assumptions_file}` into a single refined process. 
    Use clarified details from user responses to replace assumptions wherever possible, while incorporating 
    preferred assumed values only where explicitly documented. Ensure all remaining assumptions are clearly 
    linked to their relevant process steps. The consolidated process should be optimized for precision, 
    logical flow, and actionability, minimizing ambiguity and reliance on assumptions.
  expected_output: >
    Provide a detailed and actionable version of the process steps, ensuring a logical and coherent structure. 
    Replace ambiguities with clarified information and explicitly reference any remaining assumptions 
    alongside the relevant steps for transparency. Each step should contain clear instructions, supported 
    by any necessary assumptions where clarification is not available.
    Example Output:
    **Process Step Number: Short Description**
      Substep 1: Description ...
      - Assumption: For this substep the assumed value for assumption ... will be used .
      Substep 2: Description ...
      - Assumption: For this substep the assumed value for assumption ... will be used .
      - Assumption: For this substep the assumed value for assumption ... will be used .
      Substep 3: Description ...
